table Product
	lineageTag: 7855c16c-68f4-4b19-ab88-e68450c52fc6

	column 'Product Key'
		dataType: int64
		isHidden
		lineageTag: 3c183121-4737-482c-89f9-80176b06a171
		summarizeBy: count
		sourceColumn: Product Key

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Product
		dataType: string
		lineageTag: 1394d967-5249-4a31-bf5c-b8bae9e6ea77
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	partition Product = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMjRQ0lEKzi9LVIrViVYyAvECijJzS4vBfGMQ3yW/KD8dIm8C4rvnJKZkQhVYgAR8PXXNjSBcI5B8aV5eapFSbCwA", BinaryEncoding.Base64), Compression.Deflate))),
				    #"Renamed Columns" = Table.RenameColumns(Source, {{"Column1", "Product Key"}, {"Column2", "Product"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns", {{"Product Key", Int64.Type}, {"Product", type text}})
				 in
				    #"Changed Type"

